server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud?ServerTimezone=GMT%2B8
    username: root
    password: Jiangmh220
  sql:
    init:
      mode: always
      schema-locations:
        - classpath:payment.sql         # 建表的Sql脚本
      data-locations:
        - classpath:payment-data.sql    # 插值的Sql脚本

mybatis:
  type-aliases-package: com.mofany.entities             # 所有entity别名类所在包
  mapper-locations: classpath*:mapper/*Mapper.xml

# 配置Eureka提供者，即服务的提供者
eureka:
  client:
    register-with-eureka: true  # 表示是否将自己注册进Eureka-Server默认位true
    # 是否从Eureka—Server抓取已有的注册信息，默认位true
    # 单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka  # 集群版
  instance:
    instance-id: payment8001    # 显示主机名
    prefer-ip-address: true     # 显示IP地址