server:
  port: 7001

# 配置Eureka服务注册中心
eureka:
  instance:
    hostname: eureka7001.com # eureka服务端的实例名称
  client:
    register-with-eureka: false # false表示不向注册中心注册自己
    fetch-registry: false # false表示自己是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      # 设置与Eureka server交互的地址查询服务和注册服务都需要依赖这个地址
      # 集群版，与7002相互守望
#      defaultZone: http://eureka7002.com:7002/eureka/
      # 单机版
      defaultZone: http://eureka7001.com:7001/eureka/
# 禁止自我保护
  server:
    enable-self-preservation: false       # 禁用Eureka自我保护
    eviction-interval-timer-in-ms: 2000   # 多长时间清除无用服务，ms